spring:
  datasource:
    username: postgres
    password: BapQTXc3WMZXG0CKjpst
    url: jdbc:postgresql://containers-us-west-29.railway.app:6508/railway
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
